services:
  autoscaler-webhook:
    image: ghcr.io/psimsa/github-actions-autoscaler:v2.0
    ports:
      - "8080:8080"
    environment:
      - App__Mode=Webhook
      - Queue__Provider=AzureStorageQueue
      - Queue__AzureStorageQueue__ConnectionString=${AZURE_STORAGE_CONN}
      - Queue__AzureStorageQueue__QueueName=workflow-job-queued
